### ISSUE TITLE
Implement data model for MVP

### ISSUE THREAD

**Issue by veksen** [veksen/factorio-builds#18]

**Comment by kenperkins** [comment]
Are we expecting to store any metadata outside of the BP? Also how much of the blueprint to we want to denormalize into the database? Things like counts of items vs just "uses-red-belts" or whatever.

I'm thinking of at least 3 model so far, names are just representative, fields will grow as we refine.

- Blueprint
  - id
  - encoded bp string
  - owner_id
  - stats (tbd what this is, if at all in the model)
  - created/updated
  
- Metadata
  - id
  - name

- Person
  - id
  - email
  - nickname
  - created/updated

And a relation table between metadata and blueprint.

**Comment by veksen** [comment]
I'm undecided between letting the blueprint be the source of truth.

I think:

- Stuff like count of items should be kept in the blueprint, I would not denormalize it
- Stuff like best-guess of metadata based on blueprint should be denormalized: it's really a best guess: I think we want users/community to be able to change metadata

My little wishlist for blueprint/build metadata (I don't know where this belongs)

- Game state (early/mid/late)
- Category (balancer, smelting, trains, production, power...?)
- Is tileable (+tileable x times?)
- Inputs marked (filter interter/constant combinator)
- ...?

**Comment by veksen** [comment]
This is pretty much done, iterate on this in new issues.
