### ISSUE TITLE
Lighten up build listing query + json footprint

### ISSUE THREAD

**Issue by veksen** [veksen/factorio-builds#185]
The homepage loads the complete build data, which is not necessary, and could become considerably heavy as the app grows in size.

Shrink down the query to select just what's needed.
Maybe create a TS interface to go along with it.

**Comment by kenperkins** [comment]
Is it better to define a new interface here or have some of the properties nullable?

**Comment by veksen** [comment]
I'm not sure what's best practice working with TypeORM, I've been feeling like using the entity as a type is less than ideal as it doesn't really reflect what is really available, especially with types for relationships (owner vs ownerId).

Really up to trying things, but I'd be okay even without a new interface.

**Comment by kenperkins** [comment]
Is that this? https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#partial-selection

**Comment by veksen** [comment]
yes or https://github.com/typeorm/typeorm/blob/master/docs/find-options.md

**Comment by kenperkins** [comment]
I have a working query of this, except that the index page has an expectation that the blueprint is present:

```ts
    const builds = await buildRepository.createQueryBuilder("build").select([
      "build.id",
      "build.name",
      "build.metadata",
      "build.blueprint",
      "build.image"
    ])
      .where("build.image IS NOT NULL")
      .getMany()
      .catch((error) => {
        console.error(error)
        throw new Error("Cannot find build data")
      })

    const deserializedBuilds: Build[] = JSON.parse(JSON.stringify(builds))

    // temp until part of data structure/metadata
    const tempBuilds = deserializedBuilds.map((build) => {
      const decodedBlueprint = decodeBlueprint(build.blueprint)
      return {
        ...build,
        isBook: isBook(decodedBlueprint),
      }
    })
```

**Comment by kenperkins** [comment]
I would leave out the `build.blueprint` part but the logic below depends on it.

**Comment by kenperkins** [comment]
Because of this, I'd probably consider leaving this as is until we decide to refactor the models.

**Comment by veksen** [comment]
Sure we can leave `blueprint` until `isBook` is part of the metadata
