### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by veksen** [veksen/factorio-builds#30]
This includes whatever is necessary for Next to run, and attach itself to Postgres

Most likely a pre-req to deployment?

**Comment by kenperkins** [comment]
Currently blocked on this as `yarn build` or `npm run build` both try to build a "production" deployment, which is attempting to connect to a production database in the build phase.

**Comment by veksen** [comment]
is it still blocked? what does it need?

one thing I noticed is that with the current state of the app I cannot build on CI, as there is no available Postgres database. I could maybe use Travis' Postgres service..

**Comment by veksen** [comment]
Process is somewhat started with a Dockerfile used for Redis

**Comment by veksen** [comment]
Could use improvements but I'll consider this done
