### ISSUE TITLE
Retrieve images for all items

### ISSUE THREAD

**Issue by veksen** [veksen/factorio-builds#39]
We need the icons for every item in the game in order to use the to display next to build required items (and possibly somewhere else).

The images are available here: https://wiki.factorio.com/Items

The images should be named matching their factorio "data" name, for example `express-transport-belt`, `express-splitter`, `express-underground-belt`

**Comment by kenperkins** [comment]
Was this sufficiently addressed by #43?

**Comment by veksen** [comment]
yes!
